class User(name: String, var lastName: String = "lastName", var age: Int = 0) {
    var name: String = name
//        getters and setters are automatically generated by kotlin
        get() {
            return field
        }
        set(value) {
            field = value
        }
//    allows to assign value latter needs to be initialized before use
//    only work with classes (Objects) for example Int won't work
    lateinit var favoriteMove: String
//    secondary constructor, needs to call primary constructor
    constructor(name: String) : this(name, "", 0)

//    constructor can call other constructors
    constructor() : this("")


    constructor(name: String, lastName: String) : this(name, lastName, 0) {
        println("Secondary constructor")
    }

    // initialization constructor
    init {
        println("First init")
        if (name.trim().lowercase().startsWith("d")) {
            this.name = name
        } else {
            this.name = "User"
            println("This name does not start with 'd' or 'D'")
        }
    }

    init {
        println("Second init block")
    }


    override fun toString(): String {
        return this.name + ", ${this.lastName} " + this.age
    }
}